[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "npm run db:migrate:deploy"
startCommand = "npm run db:migrate:deploy && npm run start --workspace=@uln/web"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
